Sprint 3/step 1
AlexSarva/react-burger pull request #5
Opened 2023-07-03 01:59 UTC by AlexSarva

2023-07-03 03:38 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/dQvekb5auik_xw> - по умолчанию пароля быть не должно;

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

- В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/CezRCL1b_T1hjg>;

- Нужно поменять расширение файлов у редьюсеров с `.jsx` на `.js`;

- Вам нужно делать запрос ингредиентов и пользователя в компоненте `app`. Это самый оптимальный вариант.

  ```js
  // пример
  useEffect(() => {
    dispatch(getIngredients());
    dispatch(getUser());
  }, []);
  ```

  Таким образом запросы будут выполняться только 1 раз, при 1 рендере приложения.

- По чек-листу, требуется реализовать:

  - `/reset-password` доступен неавторизованным пользователям только после посещения маршрута `/forgot-password` и ввода адреса электронной почты для восстановления пароля;

  - Роуты `/profile` и все вложенные в `/profile` маршруты доступны только авторизованным пользователям, т. е. защищены HOC-компонентом ProtectedRoute.

  - При попытке неавторизованных пользователей перейти на защищённые роуты происходит редирект на `/login`. После успешной авторизации происходит переадресация на тот маршрут, к которому пользователь не получил доступ ранее. Подсказка: это делается в компоненте `protect-route` (у вас немного по другому называется - `require-auth` и `restrict-auth`) c помощью `location`;

  - Если пользователь отредактировал данные в форме, то появляются кнопки "Отмена" и "Сохранить".
    При нажатии кнопки "Сохранить" на странице профиля пользователя отправляется соответствующий запрос к Api содержащий измененные данные.
    При нажатии кнопки "Отмена" значения полей формы возвращаются в состояние до редактирования, а кнопки "Отмена" и "Сохранить" скрываются.
    А также в поле `имя` должны подтягиваться данные с профиля;
    <https://disk.yandex.com/i/BcQ_pgHTWncZfA>

  - Вам нужно проверить запросы, некоторые их них (`POST /login`, `POST /order`, `PATCH /user`) должны посылать `accessToken`. При запросах использующих accessToken проверяется ответ сервера. Если время жизни токена истекло, то выполняется запрос обновления токена и повторяется запрос, который не был выполнен успешно.

### **Сделает код лучше:**

- оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

  ```js
  <>
    <div>.....</div>
    <div>.....</div>
  </>
  ```

  <https://ru.reactjs.org/docs/fragments.html>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-07-03 03:38 UTC, ArslanMustafin commented on src/utils/auth-api.js
> +  }
**Надо исправить:**

Здесь и далее. Там, где вы передаёте токен в запрос.

Вы должны делать проверку на истечение токена, если токен истёк, вы должны получить новый, и снова сделать запрос.

Лучше сделать отдельный запрос, который будет проверять истёк ли токен, или нет.
Обрабатывать ошибки запросов и при возникновении ошибки jwt expired и вызывать обновление токена при ошибке

Для этого используйте обертку над fetch, примерно такую

```js
// например вот так
export const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options);
    return await checkResponse(res);
  } catch (err) {
    if (err.message === 'jwt expired') {
      const refreshData = await refreshToken();
      if (!refreshData.success) {
        Promise.reject(refreshData);
      }
      localStorage.setItem('refreshToken', refreshData.refreshToken);
      setCookie('accessToken', refreshData.accessToken);
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options);
      return await checkResponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

2023-07-03 03:38 UTC, ArslanMustafin commented on src/hoc/require-auth.js
> +  }, [dispatch, isLogged])
**Надо исправить:**

В этом компоненте  (и в другом похожем), не должно быть запросов на сервер. Запрос на получение пользователя должен быть в компоненте `app`.
Вы должны тут просто дождаться получение пользователя и проверить авторизован он или нет.

Оптимальный пример компонента ProtectRoute:

```js
export const ProtectedRoute = ({ onlyUnAuth = false, children }) => {
  const isAuthChecked = useSelector((state) => state.user.isAuthChecked);
  const user = useSelector((state) => state.user.data);
  const location = useLocation();

  if (!isAuthChecked) {
    return <Preloader />;
  }

  if (onlyUnAuth && user) {
    const { from } = location.state || { from: { pathname: "/" } };
    return <Navigate to={from} />;
  }

  if (!onlyUnAuth && !user) {
    return (
      <Navigate 
        to="/login"
        state={{ from: location }}
      />
    );
  }

  return children;
};

// использование 

<Route
  path="/register"
  element={
    <ProtectedRoute onlyUnAuth={true}>
      <Register />
    </ProtectedRoute>
  }
/>

<Route
  path="/profile"
  element={
    <ProtectedRoute>
      <Profile />
    </ProtectedRoute>
  }
/>
```

2023-07-03 03:38 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
>      <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-07-03 03:38 UTC, ArslanMustafin commented on src/components/pages/forgot-password/forgot-password.jsx
> +          : mutation.isSuccess
**Можно лучше:**

Что-то вы переборщили с условиями.

вот так намного легче это читается.

```js
if(mutation.isLoading) return <Preloader/>;

if(mutation.isError) 
    return <ApiError onRetry={() => mutation.reset()} message={mutation.error}/>;
                      
return (
 <>
   ...
 </>  
)

```

2023-07-03 03:38 UTC, ArslanMustafin commented on src/components/pages/ingredient/ingredient.jsx
> +  }, [dispatch, ingredient])
**Надо исправить:**

запрос ингредиентов должен быть в компоненте `app`.

2023-07-03 03:38 UTC, ArslanMustafin commented on src/components/pages/login/login.jsx
> +  }, [isLogged, navigate])
**Надо исправить:**

данная проверка должна выполняться в `protect-route`

2023-07-03 03:38 UTC, ArslanMustafin commented on src/components/pages/main/main.jsx
> +  }, [dispatch, status])
**Надо исправить:**

А точно это тут должно находиться?) просто не оч понятно зачем это нужно, а вот если бы это было в `burger-constructor`, то тогда было бы понятнее.

2023-07-03 03:38 UTC, ArslanMustafin commented on src/components/pages/profile/profile.jsx
> +    console.log('logout')
**Надо исправить:**

у вас не должно быть лишних логов в приложении.

2023-07-03 03:38 UTC, ArslanMustafin commented on src/components/pages/profile/profile.jsx
> +                  <button type="submit" style={{ display: 'none' }}></button>
Так вот почему кнопки не видно :)

2023-07-03 03:38 UTC, ArslanMustafin commented on src/components/pages/register/register.jsx
> +  }, [isLogged, navigate])
**Надо исправить:**

данная проверка должна выполняться в `protect-route`

2023-07-03 03:38 UTC, ArslanMustafin commented on src/utils/ingredients-api.js
>    const getOrderNumber = (payload) => {
**Надо исправить:**

Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали); Не забудьте про проверку `jwt expired`.

2023-07-05 21:22 UTC, AlexSarva commented on src/utils/auth-api.js
> +  }
done

2023-07-05 21:22 UTC, AlexSarva commented on src/hoc/require-auth.js
> +  }, [dispatch, isLogged])
done

2023-07-05 21:23 UTC, AlexSarva commented on src/components/burger-ingredients/burger-ingredients.jsx
>      <>
done

2023-07-05 21:38 UTC, AlexSarva commented on src/components/pages/forgot-password/forgot-password.jsx
> +          : mutation.isSuccess
done

2023-07-05 21:38 UTC, AlexSarva commented on src/components/pages/ingredient/ingredient.jsx
> +  }, [dispatch, ingredient])
done

2023-07-05 21:45 UTC, AlexSarva commented on src/components/pages/login/login.jsx
> +  }, [isLogged, navigate])
done

2023-07-05 21:47 UTC, AlexSarva commented on src/components/pages/main/main.jsx
> +  }, [dispatch, status])
done

2023-07-05 21:50 UTC, AlexSarva commented on src/components/pages/profile/profile.jsx
> +    console.log('logout')
done

2023-07-05 21:54 UTC, AlexSarva commented on src/components/pages/register/register.jsx
> +  }, [isLogged, navigate])
done

2023-07-05 21:57 UTC, AlexSarva commented on src/utils/ingredients-api.js
>    const getOrderNumber = (payload) => {
done

2023-07-06 00:24 UTC, AlexSarva commented on src/components/pages/profile/profile.jsx
> +                  <button type="submit" style={{ display: 'none' }}></button>
done, хотя в макете не нашел нормальную информацию, как должны выгрузить кнопки и какое у них должно быть поведение

2023-07-06 04:14 UTC, ArslanMustafin commented on src/components/pages/profile/profile.jsx
> +                  <button type="submit" style={{ display: 'none' }}></button>
Там в макете есть исходники https://disk.yandex.com/i/ocE5kj3VCNxIxA)) а так да, вы правы, их сложновато найти.

2023-07-06 04:15 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-07-22 15:45 UTC, merged